function [ A_out, t_out, T_out, W_out ] = HQR_unb_var3( A, t, T, W )

  [ ATL, ATR, ...
    ABL, ABR ] = FLA_Part_2x2( A, ...
                               0, 0, 'FLA_TL' );

  [ tT, ...
    tB ] = FLA_Part_2x1( t, ...
                         0, 'FLA_TOP' );

  [ TTL, TTR, ...
    TBL, TBR ] = FLA_Part_2x2( T, ...
                               0, 0, 'FLA_TL' );

  [ WTL, WTR, ...
    WBL, WBR ] = FLA_Part_2x2( W, ...
                               0, 0, 'FLA_TL' );

  %  while ( size( ATL, 2 ) < size( A, 2 ) )
    while ( size( ATL, 2 ) < size( t, 1 ) )

    [ A00,  a01,     A02,  ...
      a10t, alpha11, a12t, ...
      A20,  a21,     A22 ] = FLA_Repart_2x2_to_3x3( ATL, ATR, ...
                                                    ABL, ABR, ...
                                                    1, 1, 'FLA_BR' );

    [ t0, ...
      tau1, ...
      t2 ] = FLA_Repart_2x1_to_3x1( tT, ...
                                    tB, ...
                                    1, 'FLA_BOTTOM' );

    [ T00,  t01,   T02,  ...
      t10t, tau11, t12t, ...
      T20,  t21,   T22 ] = FLA_Repart_2x2_to_3x3( TTL, TTR, ...
                                                  TBL, TBR, ...
                                                  1, 1, 'FLA_BR' );

    [ W00,  w01,     W02,  ...
      w10t, omega11, w12t, ...
      W20,  w21,     W22 ] = FLA_Repart_2x2_to_3x3( WTL, WTR, ...
                                                    WBL, WBR, ...
                                                    1, 1, 'FLA_BR' );

    %------------------------------------------------------------%
    10
    % Update according to prior computation
    alpha11 = alpha11 - a10t * w01;    
    11
    a21 = a21 - A20 * w01;
    12
    a12t    = a12t - a10t * W02;
    13

    % Compute Householder vector and update alpha11 and a21
    [ alpha11, ...
      a21, tau1 ] = Housev( alpha11, ...
                              a21 );
    
    % Update W
    w12t = ( a12t + a21' * A22 - ( a21' * A20 ) * W02 ) / tau1;
    
    % Update a12t according to current computation
    a12t = a12t - w12t;
    
    % Update T
    t01 = a10t' + A20' * a21;
    tau11 = tau1;
    
    %------------------------------------------------------------%

    [ ATL, ATR, ...
      ABL, ABR ] = FLA_Cont_with_3x3_to_2x2( A00,  a01,     A02,  ...
                                             a10t, alpha11, a12t, ...
                                             A20,  a21,     A22, ...
                                             'FLA_TL' );

    [ tT, ...
      tB ] = FLA_Cont_with_3x1_to_2x1( t0, ...
                                       tau1, ...
                                       t2, ...
                                       'FLA_TOP' );

    [ TTL, TTR, ...
      TBL, TBR ] = FLA_Cont_with_3x3_to_2x2( T00,  t01,   T02,  ...
                                             t10t, tau11, t12t, ...
                                             T20,  t21,   T22, ...
                                             'FLA_TL' );

    [ WTL, WTR, ...
      WBL, WBR ] = FLA_Cont_with_3x3_to_2x2( W00,  w01,     W02,  ...
                                             w10t, omega11, w12t, ...
                                             W20,  w21,     W22, ...
                                             'FLA_TL' );

  end

  A_out = [ ATL, ATR
            ABL, ABR ];

  t_out = [ tT
            tB ];

  T_out = [ TTL, TTR
            TBL, TBR ];

  W_out = [ WTR
            WBR ];

return

